[tool.poetry]
name = "ivi_test"
version = "0.1.0"
description = "scripts for api testing"
authors = ["Ana Peshkova"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
